services:
###> shopware/core ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: shopware
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql:rw
    command:
      - --default-time-zone=+00:00
      - --innodb_buffer_pool_size=1024M
      - --innodb_log_file_size=128M
      - --max_allowed_packet=256M
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      start_period: 10s
      interval: 5s
      timeout: 1s
      retries: 10
###< shopware/core ###

###> shopware/elasticsearch ###
  opensearch:
    image: opensearchproject/opensearch:2
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'c3o_ZPHo!'
      discovery.type: single-node
      plugins.security.disabled: 'true'
###< shopware/elasticsearch ###

volumes:
###> shopware/core ###
  db-data:
###< shopware/core ###

###> shopware/elasticsearch ###
  opensearch-data:
###< shopware/elasticsearch ###
